version: '3'
services:
  edelweissapp:
    container_name: ${APP_SERVICE_NAME}
    image: 'edelweissapp/dev'
    ports:
      - "${SSH_PORT}:22"
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${FREE_PORT}:8080"
      - "${SUPERVISOR_UI_PORT}:9002"
    env_file: ./.env
    volumes:
      - ${DATA_FOLDER}/feed:/var/www/feed
      - ${DATA_FOLDER}/profile:/var/www/profile
      - ${DATA_FOLDER}/app:/var/www/app
      - ${DATA_FOLDER}/auth:/var/www/auth
      - ${DATA_FOLDER}/vhost:/etc/nginx/sites-enabled:ro
    restart: always
    tty: true
  mariadb:
    container_name: ${DB_SERVICE_NAME}
    image: 'bitnami/mariadb:latest'
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - ${DATA_FOLDER}/mariadb:/bitnami
  redis:
    container_name: ${REDIS_SERVICE_NAME}
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ${DATA_FOLDER}/redis:/bitnami
  rabbitmq:
    container_name: ${RABBITMQ_NAME}
    image: bitnami/rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=/