version: '3'
services:
  redmon:
    container_name: ${REDMON_NAME}
    image: vieux/redmon
    depends_on:
      - redis
    ports:
      - "${REDMON_PORT}:4567"
    command: -r redis://:${REDIS_PASSWORD}@redis:6379